#!/bin/sh

# Create a sed script from mcu_replacement_bitfield.txt

#sed 's/\(.*\)/s\/\1//gi/' mcu_replacement_bitfield.txt > sed_script.sed
# Apply the sed script to the source file and save the result
#sed -f sed_script.sed source-out.fs.stripped > source-out.fs.replaced

#sed 's/\(.*\)\s*\(.*\)/s\/\1\/\2\/gi/' mcu_replacement_bitfield.txt > sed_script.sed

awk '{printf("s/%s/%s/gi\n", $1, $2)}' mcu_replacement_bitfield.txt > sed_script.sed

